### ISSUE TITLE
Feature Request, kill client

### ISSUE THREAD

**Issue by camjac251** [Arcanemagus/plexWatchWeb#5]
I have people on my server who just start something up (transcoding, of course :/, putting load on the vps) and then just leave it paused for days. I'd like to kill those clients so they aren't wasting bandwidth and slowing it down. PlexSentry claims to have a similar function but would rather use 1 app for everything instead of 2 https://forums.plex.tv/index.php/topic/156041-plexsentry

**Comment by Arcanemagus** [comment]
The author of PlexSentry hasn't posted source code, so I have no idea how they are trying to accomplish that, but as they state in their post that only works for clients on the local network, and only if they are opened up to accepting local commands... As far as I know there is no API / REST call you can make to a Plex server to cause it to stop a client's stream. As a note, the guy who is making that has left quite a bit of his personal info strewn all over the code, so I'm not sure how well any of that code will work if he isn't able to clean that out before distributing it...

Since the entire point of plexWatch(/Web) is to simply provide much easier access to the usage information of your Plex server and not manage the server itself this isn't really something that is appropriate for this project anyway.

**Comment by Arcanemagus** [comment]
I'm going to close this for now, if Plex ever puts this into the official server (or at least documents some API to do it) then maybe this can be revisited.
